import calendar
import datetime
calenders=calendar.month(2023,5)
print(calenders)
print(calendar.prcal(2024))
print(calendar.TextCalendar(calendar.TUESDAY).formatyear(2322))
from datetime import date
date1=date(2023,3,4)
date2=date(2024,3,23)
diff=date2-date1
print(diff.days)
dt1=datetime.datetime.today()
print(dt1)
print(dt1.strftime("%A"))
print(dt1.strftime("%a"))
print(dt1.strftime("%w"))
print(dt1.strftime("%d"))
print(dt1.strftime("%y"))
print(dt1.strftime("%Y"))
print(dt1.strftime("%H"))
print(dt1.strftime("%B"))
print(dt1.strftime("%S"))
print(dt1.strftime("%M"))
print(dt1.strftime("%p"))
print(dt1.strftime("%W"))
print(dt1.strftime("%b"))
xx=int(input("input year"))
yy=int(input("input month"))
print(calendar.month(xx,yy))
print("Mohd   ... ")
print("Anas")
print("Mohd","Anas","Ansari",sep='\t',end='')
print(calendar.calendar(2020,2,1,6))
print(calendar.calendar(2020,2,1,6))
print("The starting day number in calendar is : ",end='')
print(calendar.firstweekday())
print("The number of leapyears between -2022 to 2022")
print(calendar.leapdays(-2022,2022))

